version: '3.8'

services:
  aureus-redis:
    image: redis:alpine
    container_name: aureus_redis
    restart: always
    command: >
      redis-server
      --databases 16
    ports:
      - "6379:6379"
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_HOST: ${DATABASE_HOST}
    volumes:
      - aureus-db:/var/lib/redis/data

  aureus_timescaledb:
    image: timescale/timescaledb:2.14.2-pg16
    restart: always
    container_name: aureus_timescaledb
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - aureus-db:/var/lib/timescaledb/data

volumes:
  aureus-db:
